import { notFound } from 'next/navigation';
import Link from 'next/link';
import { getProduct, formatZar } from '../../../../lib/products';
import { ProductActions } from './ProductActions';

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const product = await getProduct((await params).slug); return product ? { title: `${product.name} | CHEFU Store`, description: product.seoDescription || product.description, alternates: { canonical: `/store/products/${product.slug}` } } : { title: 'Product not found | CHEFU Store' }; }

export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) {
  const product = await getProduct((await params).slug); if (!product) notFound();
  const unavailable = product.status === 'OUT_OF_STOCK' || product.inventoryQuantity < 1;
  return <main className="min-h-screen bg-slate-950 px-6 pb-24 pt-36 text-slate-100"><div className="mx-auto max-w-6xl"><Link href="/store" className="text-sm text-slate-400 hover:text-cyan-300">← Back to store</Link><div className="mt-10 grid gap-12 lg:grid-cols-2"><div className="flex aspect-square items-center justify-center rounded-3xl border border-slate-800 bg-slate-900 p-10">{product.thumbnail || product.images[0]?.url ? <img src={product.thumbnail || product.images[0]?.url} alt={product.images[0]?.alt || product.name} className="max-h-full w-full object-contain" /> : <span className="text-[10rem] font-bold text-slate-700">C</span>}</div><div className="flex flex-col justify-center"><p className="text-sm font-semibold uppercase tracking-[0.25em] text-cyan-400">{product.category}</p><h1 className="mt-4 text-5xl font-bold tracking-tight">{product.name}</h1><p className="mt-5 text-2xl font-semibold">{formatZar(product.priceMinor)}</p><p className="mt-6 text-lg leading-8 text-slate-400">{product.description || product.shortDescription}</p><p className={`mt-6 text-sm ${unavailable ? 'text-rose-300' : 'text-emerald-300'}`}>{unavailable ? 'Currently unavailable' : product.inventoryQuantity <= product.lowStockThreshold ? `Only ${product.inventoryQuantity} left` : 'In stock'}</p><ProductActions product={product} disabled={unavailable} /></div></div></div></main>;
}